### ISSUE TITLE
PyVISA 1.12.0 and GPIB Secondary Addresses

### ISSUE THREAD

**Issue by Satertek** [pyvisa/pyvisa-sim#58]
PyVISA 1.12.0 introduced a change to how GPIB secondary addresses are handled.  An undefined secondary address is now returned as a [None instead of "0"](https://github.com/pyvisa/pyvisa/blob/main/pyvisa/rname.py#L354).  This [breaks pyvisa-sim](https://github.com/pyvisa/pyvisa-sim/blob/33de1e4a2466d210cc038c305637f3933454eb92/pyvisa_sim/gpib.py#L27) when loading a GPIB instrument address that does not contain a secondary address, raising `TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'`

I'm not sure what the best solution would be for pyvisa-sim.  My personal workaround is to just define a secondary address in my test cases.
  
Example:
```
> rm = pyvisa.highlevel.ResourceManager("@sim")
> inst = rm.open_resource("GPIB::1::INSTR")
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>  
  File "./python3.10/site-packages/pyvisa/highlevel.py", line 3284, in open_resource
    res.open(access_mode, open_timeout)  
  File "./python3.10/site-packages/pyvisa/resources/resource.py", line 278, in open
    self.session, status = self._resource_manager.open_bare_resource(
  File "./python3.10/site-packages/pyvisa/highlevel.py", line 3209, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)  
  File "./python3.10/site-packages/pyvisa_sim/highlevel.py", line 121, in open
    sess = cls(session, resource_name, parsed)
  File "./python3.10/site-packages/pyvisa_sim/sessions.py", line 79, in __init__
    self.after_parsing()
  File "./python3.10/site-packages/pyvisa_sim/gpib.py", line 33, in after_parsing
    self.attrs[constants.VI_ATTR_GPIB_SECONDARY_ADDR] = int(self.parsed.secondary_address)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by Satertek** [comment]
May be as simple as:

```
index ccbbe75..a92d324 100644
--- a/pyvisa_sim/gpib.py
+++ b/pyvisa_sim/gpib.py
@@ -24,9 +24,10 @@ class GPIBInstrumentSession(sessions.Session):
         self.attrs[constants.VI_ATTR_GPIB_PRIMARY_ADDR] = int(
             self.parsed.primary_address
         )
-        self.attrs[constants.VI_ATTR_GPIB_SECONDARY_ADDR] = int(
-            self.parsed.secondary_address
-        )
+        if self.parsed.secondary_address is not None:
+            self.attrs[constants.VI_ATTR_GPIB_SECONDARY_ADDR] = int(
+                self.parsed.secondary_address
+            )

     def read(self, count):
         end_char, _ = self.get_attribute(constants.VI_ATTR_TERMCHAR)
```
